# Header
nav:
  Posts: /archives
# Categories: /category
# Tags: /tag

# favicon
favicon: /blog/images/favicon.ico

# logo
logo: /blog/images/logo.png

# links
links:
  Github: https://github.com/sunbooshi
  # ZhiHu:
  # Twitter:
  # Weibo:

# analytics
google_analytics: 
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

# disqusjs
disqusjs:
  enable: false
  api:
  apikey:
  shortname: